### ISSUE TITLE
hi  im tryng to open options  click on ur red button is there way to re install  this ui in game having issue

### ISSUE THREAD

**Issue by darmentle** [nihilistzsche/ElvUI_NihilistzscheUI#1]
**Description**

**NihilistzscheUI Version**

**ElvUI Version**

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

**Actual Behavior**

**Mention what addons you are using.**

**Additional Information**

**Error Log**

```

```

**Comment by nihilistzsche** [comment]
It has not been updated for the patch that has dropped today, but will be as soon as I am able.

**Comment by darmentle** [comment]
Ty i love the ui!
