### ISSUE TITLE
Instller?

### ISSUE THREAD

**Issue by darmentle** [nihilistzsche/ElvUI_NihilistzscheUI#4]
how is it going did you ever get the installer working ?

**Is your feature request related to a problem? Please describe.**
A description of what your problem is.

**Describe the final outcome you would except**
A description of what you want to happen or would be ok with if not exactly able to do that.

**Describe other alternative ideas/addons you have considered**
A description of any alternative solutions or features you havve considered.  Sometimes it's better to use another addon if it has what you want.

**Additional info**
Add any other information or screenshots about the feature request to help illustrate.

**Comment by nihilistzsche** [comment]
Yes the installer should be working fine now, theres not much to say about it, it literally does the following:

Installs class based profiles for every class seen in ElvUI.lua with my personal setup, while at the same time doing things for other addons that I use that I set things up for.  Using it will get you the exact same UI you see in my screenshots, nothing else, there are no options for it, its just my profile and go.  It was meant mainly for me that if my WTF ever goes boom I have an easy way to get back.  Do let me know if you run into any issues.
