### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by Snowmanmc87** [nihilistzsche/ElvUI_NihilistzscheUI#5]
**Description**

1.I dont have a installer for NihilistUI .

**NihilistzscheUI Version**

12.054
**ElvUI Version**

12.99

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

**Actual Behavior**

**Mention what addons you are using.**

**Additional Information**

i tried a clean install, i delete everything ElvUI related from my addons folder.
Then i installed Elvui , NihilistUI, Shadow & Light, BenikUi and MerathilisUi.
I also tried just Elvui and NihilistUI. still no installer. 
I have been using Elvui for a long time never really had problem installing New Ui.

I really like how your Ui looks . you put so Much time and afford in it, but i cant get it to work. (:

**Error Log**

```

```

**Comment by nihilistzsche** [comment]
Can you upload your ElvUI.lua SavedVariables please?

**Comment by Snowmanmc87** [comment]
How do i do that, it wont let me upload the file here, and the text is to long to past here.

**Comment by nihilistzsche** [comment]
post it into a gist (gist.github.com) and post a link here.

**Comment by Snowmanmc87** [comment]
https://gist.github.com/Snowmanmc87/fc3e570e5cb7f91e03deac253438d737

**Comment by nihilistzsche** [comment]
It looks like NihilistzscheUI installed in there, so can you also share your ElvUI_Nihilistzsche_Installer.lua SavedVariables?

**Comment by Snowmanmc87** [comment]
https://gist.github.com/Snowmanmc87/2af0e3c15a86e0d99978585bf632c039

**Comment by nihilistzsche** [comment]
Thanks, the version is old so the installer should be popping up.  Ill take a look later today with the provided files to try to figure out why it won't.

**Comment by Snowmanmc87** [comment]
ok thanks, do u think i might help to do a clean install of WoW to fix the problem ?

**Comment by nihilistzsche** [comment]
I suspect you have a Lua error somewhere in the installer, so no I do not.

**Comment by nihilistzsche** [comment]
Can you check again with 12.07 and tell me if you still dont see the installer?

**Comment by Snowmanmc87** [comment]
So i tried 12.07 there was a 2 step installer at first . but when i go into elvui there is no installer and i am getting a lot of Lua Errors

**Comment by Snowmanmc87** [comment]
Also tried 12.07-1 same thing

**Comment by nihilistzsche** [comment]
Okay, so the lua errors imply there was a lua error in the installer, if you have bugack/buggrabber installed, you can scroll back and I need you to find one that mentions ElvUI_NihilistzscheUI_Installer

**Comment by Snowmanmc87** [comment]
ok let me download that real fast.

**Comment by Snowmanmc87** [comment]
Sorry dont see anything with Installer.

**Comment by Snowmanmc87** [comment]
2x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_NihilistzscheUI_Installer' tried to call the protected function 'Reload()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Reload'
[string "@Interface/SharedXML/InterfaceUtil.lua"]:2: in function `ReloadUI'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI_Installer/core/installer_utility.lua"]:480: in function <...NihilistzscheUI_Installer/core/installer_utility.lua:477>

**Comment by nihilistzsche** [comment]
I've never run into that problem, seems like something is tainting that.  What addons do you have installed?

**Comment by Snowmanmc87** [comment]
i disabled all addons for testing. So i dont think it is that.

**Comment by Snowmanmc87** [comment]
I really dont understand why it doesn't work, all the other ElvUi installers work fine.

**Comment by nihilistzsche** [comment]
I just ran my installer successfully a few minutes ago, and without a good error I cant really track what could be going wrong.

**Comment by Snowmanmc87** [comment]
So how many steps does your installer have ? and after you run it does it show up in the elvUi settings ?

**Comment by nihilistzsche** [comment]
Just 2, the intro and then the last step first button sets everything up, second just sets the installed version but does not do anything, and the third is a button for a discord that doesnt exist anymore and I will remove soon.

**Comment by Snowmanmc87** [comment]
after you install it does it show up in the Elvui setting ?

**Comment by nihilistzsche** [comment]
Yes, and should even before you install it.

**Comment by Snowmanmc87** [comment]
Ok ill try a clean install of WoW , maybe some old addon or something fucking things up. I don't think that is the case seens the other installers work ,but ill try

**Comment by Snowmanmc87** [comment]
Ok i did a fresh install, now i have your installer. But i am getting a lot of Lua Error, and i have no Unit frames.

**Comment by Snowmanmc87** [comment]
Message: bad argument #4 to '?' (Usage: local line = self:CreateFontString([name, drawLayer, templateName]))
Time: Thu Nov 10 15:20:01 2022
Count: 1
Stack: bad argument #4 to '?' (Usage: local line = self:CreateFontString([name, drawLayer, templateName]))
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CreateFontString'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibCandyBar-3.0/LibCandyBar-3.0/LibCandyBar-3.0.lua"]:480: in function `New'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/raidcds/utility/frames.lua"]:31: in function `CreateBar'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/raidcds/core/raidcds.lua"]:100: in function `UpdateCDs'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/raidcds/utility/players.lua"]:69: in function `InspectPlayer'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/raidcds/utility/players.lua"]:25: in function `?'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:114: in function <...Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua"]:928: in function `Rescan'
...
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/raidcds/core/raidcds.lua"]:265: in function `Initialize'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/init.lua"]:129: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/init.lua"]:146: in function `?'
[string "@Interface/AddOns/ElvUI/Libraries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua"]:299: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:295>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:226: in function <Interface/AddOns/ElvUI/Core/init.lua:225>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

**Comment by Snowmanmc87** [comment]
Is there a specific way i have to setup elvui to make everthing work ? or am i missing a addon ?

**Comment by Snowmanmc87** [comment]
Message: ...ElvUI_NihilistzscheUI_Installer/installers/elvui.lua:703: attempt to index field 'db' (a nil value)
Time: Thu Nov 10 15:30:58 2022
Count: 1
Stack: ...ElvUI_NihilistzscheUI_Installer/installers/elvui.lua:703: attempt to index field 'db' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_NihilistzscheUI_Installer/installers/elvui.lua"]:703: in function `ElvUISetup'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI_Installer/core/installer.lua"]:50: in function `InstallForClass'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI_Installer/core/installer.lua"]:69: in function `SetupForCharacters'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI_Installer/core/installer.lua"]:83: in function `Run'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI_Installer/core/installer.lua"]:138: in function <...s/ElvUI_NihilistzscheUI_Installer/core/installer.lua:137>

Locals:

**Comment by nihilistzsche** [comment]
The first error implies you dont have a valid font set, its one of the options on the settings page near the Install button.  The second is from a corrupted WTF though I have not been able to pinpoint the cause (I keep daily backups and when mine showed this issue I just rolled back to the files from the night before).

**Comment by nihilistzsche** [comment]
Im seeing this in the second prepatch a lot and may have way to work around the installer issue.

**Comment by nihilistzsche** [comment]
So, Im reproducing this consistently with new characters that have not logged in before, and Ill admit the experience is jarring.  However, I have found a good workaround that seems to work and so I dont think it worth spending more time trying to investigate:

If you get spamming errors and no Install window, run the following:
/run ElvUI_NihilistzscheUI[1].Installer:Initialize()
