### ISSUE TITLE
Help only working on some charcters

### ISSUE THREAD

**Issue by darmentle** [nihilistzsche/ElvUI_NihilistzscheUI#6]
**Description**

**ElvUI Version**

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

**Actual Behavior**

**Mention what addons you are using.**

**Additional Information**

**Error Log**

```

```

**Comment by nihilistzsche** [comment]
I need a lot more issue than presented here, what characters does it not work on (class, race, faction, level), do you receive any lua errors?

**Comment by darmentle** [comment]
human mage  level 19 is there a way to see the lua error

**Comment by nihilistzsche** [comment]
Don't do the original command here, that would turn NihilistzscheUI off and is not helpful, try this instead.

/run SetCVar('scriptErrors', 1);ReloadUI()

**Comment by darmentle** [comment]
I did that  whats next ? Sent from Mail for Windows From: NihilistzscheSent: Sunday, November 6, 2022 10:11 PMTo: nihilistzsche/ElvUI_NihilistzscheUICc: darmentle; AuthorSubject: Re: [nihilistzsche/ElvUI_NihilistzscheUI] Help only working on some charcters (Issue #6) /edebug on—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by darmentle** [comment]
i did it 
..istzscheUI/modules/customdatabar/tags/reputation.lua:25: attempt to index local 'data' (a nil value)
Time: Tue Nov  8 21:41:29 2022
Count: 1
Stack: ...istzscheUI/modules/customdatabar/tags/reputation.lua:25: attempt to index local 'data' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/customdatabar/tags/reputation.lua"]:25: in function <...istzscheUI/modules/customdatabar/tags/reputation.lua:23>
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/customdatabar/tags/reputation.lua"]:42: in function `evaluationFunc'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibNihilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua"]:142: in function <...hilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua:136>
[string "=[C]"]: in function `gsub'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibNihilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua"]:174: in function `UpdateTagString'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibNihilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua"]:165: in function `UpdateTagStrings'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibNihilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua"]:120: in function `Tag'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/customdatabar/core/customdatabar.lua"]:88: in function `UpdateTag'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/customdatabar/core/customdatabar.lua"]:106: in function `Initialize'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/init.lua"]:129: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/init.lua"]:146: in function `?'
[string "@Interface/AddOns/ElvUI/Libraries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua"]:299: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:295>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:226: in function <Interface/AddOns/ElvUI/Core/init.lua:225>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: 
e: ...istzscheUI/modules/customdatabar/tags/reputation.lua:25: attempt to index local 'data' (a nil value)
Time: Tue Nov  8 21:41:31 2022
Count: 3
Stack: ...istzscheUI/modules/customdatabar/tags/reputation.lua:25: attempt to index local 'data' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/customdatabar/tags/reputation.lua"]:25: in function <...istzscheUI/modules/customdatabar/tags/reputation.lua:23>
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/modules/customdatabar/tags/reputation.lua"]:42: in function `evaluationFunc'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibNihilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua"]:142: in function <...hilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua:136>
[string "=[C]"]: in function `gsub'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibNihilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua"]:174: in function `UpdateTagString'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibNihilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua"]:165: in function `UpdateTagStrings'
[string "@Interface/AddOns/ElvUI_NihilistzscheUI/libs/LibNihilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua"]:127: in function <...hilistzscheUITags-1.0/LibNihilistzscheUITags-1.0.lua:126>

Locals:

**Comment by nihilistzsche** [comment]
Thanks, see the issue and will have a fixed release out soon.

**Comment by nihilistzsche** [comment]
Fixed in 12.07

**Comment by darmentle** [comment]
Thanks
